import pandas as pd
df = pd.read_csv("healthcare_dataset.csv")
print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nFirst 5 rows:")
print(df.head())
print("\nData types:")
print(df.dtypes)
print("\nNull values:")
print(df.isnull().sum())
print("\nBasic stats:")
print(df.describe())
df["Date of Admission"] = pd.to_datetime(df["Date of Admission"])
df["Discharge Date"] = pd.to_datetime(df["Discharge Date"])
df["Length of Stay"] = (df["Discharge Date"] - df["Date of Admission"]).dt.days
df = df[df["Billing Amount"] > 0]
df["Name"] = df["Name"].str.title()
df["Admission Year"] = df["Date of Admission"].dt.year
print("Shape after cleaning:", df.shape)
print("\nNegative billing removed — Min billing now:", df["Billing Amount"].min().round(2))
print("\nLength of Stay sample:")
print(df[["Name", "Date of Admission", "Discharge Date", "Length of Stay"]].head())
print("\nYears in data:", sorted(df["Admission Year"].unique()))
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (10, 5)
# EDA 1 — Medical Condition distribution
print("=== Medical Condition Counts ===")
print(df["Medical Condition"].value_counts())
# EDA 2 — Average billing by condition
print("\n=== Avg Billing by Medical Condition ===")
print(df.groupby("Medical Condition")["Billing Amount"].mean().round(2).sort_values(ascending=False))
# EDA 3 — Average length of stay by condition
print("\n=== Avg Length of Stay by Condition ===")
print(df.groupby("Medical Condition")["Length of Stay"].mean().round(1).sort_values(ascending=False))
# EDA 4 — Admission type distribution
print("\n=== Admission Type Counts ===")
print(df["Admission Type"].value_counts())
# EDA 5 — Test results distribution
print("\n=== Test Results Distribution ===")
print(df["Test Results"].value_counts())
# EDA 6 — Yearly admissions trend
print("\n=== Yearly Admissions ===")
print(df["Admission Year"].value_counts().sort_index())
# Chart 1 — Patients by Medical Condition
plt.figure()
condition_counts = df["Medical Condition"].value_counts()
sns.barplot(x=condition_counts.index, y=condition_counts.values, palette="Blues_d")
plt.title("Patients by Medical Condition")
plt.xlabel("Medical Condition")
plt.ylabel("Number of Patients")
plt.tight_layout()
plt.savefig("chart1_medical_condition.png")
plt.show()
print("Chart 1 saved!")
# Chart 2 — Avg Billing by Condition
plt.figure()
avg_billing = df.groupby("Medical Condition")["Billing Amount"].mean().sort_values(ascending=False)
sns.barplot(x=avg_billing.index, y=avg_billing.values, palette="Greens_d")
plt.title("Average Billing Amount by Medical Condition")
plt.xlabel("Medical Condition")
plt.ylabel("Avg Billing Amount ($)")
plt.tight_layout()
plt.savefig("chart2_avg_billing.png")
plt.show()
print("Chart 2 saved!")
# Chart 3 — Length of Stay by Condition
plt.figure()
avg_stay = df.groupby("Medical Condition")["Length of Stay"].mean().sort_values(ascending=False)
sns.barplot(x=avg_stay.index, y=avg_stay.values, palette="Oranges_d")
plt.title("Average Length of Stay by Medical Condition")
plt.xlabel("Medical Condition")
plt.ylabel("Avg Days")
plt.tight_layout()
plt.savefig("chart3_length_of_stay.png")
plt.show()
print("Chart 3 saved!")
# Chart 4 — Yearly Admissions Trend
plt.figure()
yearly = df["Admission Year"].value_counts().sort_index()
plt.plot(yearly.index, yearly.values, marker="o", color="steelblue", linewidth=2.5)
plt.title("Yearly Patient Admissions Trend (2019-2024)")
plt.xlabel("Year")
plt.ylabel("Number of Admissions")
plt.tight_layout()
plt.savefig("chart4_yearly_trend.png")
plt.show()
print("Chart 4 saved!")
# Chart 5 — Test Results Distribution
plt.figure()
test_counts = df["Test Results"].value_counts()
sns.barplot(x=test_counts.index, y=test_counts.values, palette="Reds_d")
plt.title("Patient Test Results Distribution")
plt.xlabel("Test Result")
plt.ylabel("Number of Patients")
plt.tight_layout()
plt.savefig("chart5_test_results.png")
plt.show()
print("Chart 5 saved!")
# Chart 6 — Age Distribution
plt.figure()
sns.histplot(data=df, x="Age", bins=20, color="steelblue", kde=True)
plt.title("Patient Age Distribution")
plt.xlabel("Age")
plt.ylabel("Count")
plt.tight_layout()
plt.savefig("chart6_age_distribution.png")
plt.show()
print("Chart 6 saved!")